import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

// This class is automatically generated by shadcn UI.

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
