name: Python Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r mark-management-system/backend/requirements.txt

      - name: Run Tests
        run: |
          cd mark-management-system/backend/tests
          pytest
